	
using System;
using System.Linq;
using System.Text;
using System.Data;
using System.Collections.Generic;

namespace Plan.Domain
{
    // ############################################################################
    // #
    // #        ---==>  T H I S  F I L E  W A S  G E N E R A T E D  <==---
    // #
    // # This file was generated by PRO Spark, C# Edition, Version 4.5
    // # Generated on 7/25/2013 11:58:36 PM
    // #
    // # Edits to this file may cause incorrect behavior and will be lost
    // # if the code is regenerated.
    // #
    // ############################################################################
	
	// Plan Domain objects
	
    public partial class Task : Entity<Task>
	{
		public Task() { }
        public Task(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public int? UserId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
    }
	
    public partial class User : Entity<User>
	{
		public User() { }
        public User(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    }
}
