	
using System;
using System.Linq;
using System.Text;
using System.Data;
using System.Collections.Generic;

namespace Plan.Domain
{
    // ############################################################################
    // #
    // #        ---==>  T H I S  F I L E  W A S  G E N E R A T E D  <==---
    // #
    // # This file was generated by PRO Spark, C# Edition, Version 4.5
    // # Generated on 7/25/2013 11:58:36 PM
    // #
    // # Edits to this file may cause incorrect behavior and will be lost
    // # if the code is regenerated.
    // #
    // ############################################################################
	
	// Plan Context. hosts all repositories

	public static class PlanContext
	{
	    static Db db = new PlanDb();
		
		// entity specific repositories

        public static Tasks Tasks { get { return new Tasks(); } }
        public static Users Users { get { return new Users(); } }

        // general purpose operations

        public static void Execute(string sql, params object[] parms) { db.Execute( sql, parms ); }
        public static IEnumerable<dynamic> Query(string sql, params object[] parms) { return db.Query( sql, parms ); }
        public static object Scalar(string sql, params object[] parms) { return db.Scalar( sql, parms ); }

        public static DataSet GetDataSet(string sql, params object[] parms) { return db.GetDataSet( sql, parms ); }
        public static DataTable GetDataTable(string sql, params object[] parms) { return db.GetDataTable( sql, parms ); }
        public static DataRow GetDataRow(string sql, params object[] parms) { return db.GetDataRow( sql, parms ); }
	}
}
