//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForms {
    
    
    public partial class SiteMaster {
        
        
        // HeadContent control.
        
        // <remarks>
        // Auto-generated field.
        // To modify move field declaration from designer file to code-behind file.
        // </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
        
        
        // form1 control.
        
        // <remarks>
        // Auto-generated field.
        // To modify move field declaration from designer file to code-behind file.
        // </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        
        // HyperLinkLogo control.
        
        // <remarks>
        // Auto-generated field.
        // To modify move field declaration from designer file to code-behind file.
        // </remarks>
        protected global::System.Web.UI.WebControls.HyperLink HyperLinkLogo;
        
        
        // SiteMapPathMain control.
        
        // <remarks>
        // Auto-generated field.
        // To modify move field declaration from designer file to code-behind file.
        // </remarks>
        protected global::System.Web.UI.WebControls.SiteMapPath SiteMapPathMain;
        
        
        // TheMenuComposite control.
        
        // <remarks>
        // Auto-generated field.
        // To modify move field declaration from designer file to code-behind file.
        // </remarks>
        protected global::WebForms.Controls.MenuComposite TheMenuComposite;
        
        
        // ScriptManager1 control.
        
        // <remarks>
        // Auto-generated field.
        // To modify move field declaration from designer file to code-behind file.
        // </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        
        // UpdateProgress1 control.
        
        // <remarks>
        // Auto-generated field.
        // To modify move field declaration from designer file to code-behind file.
        // </remarks>
        protected global::System.Web.UI.UpdateProgress UpdateProgress1;
        
        
        // MainContent control.
        
        // <remarks>
        // Auto-generated field.
        // To modify move field declaration from designer file to code-behind file.
        // </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
