	
using System;
using System.Linq;
using System.Text;
using System.Data;
using System.Collections.Generic;

namespace Art.Domain
{
    // ############################################################################
    // #
    // #        ---==>  T H I S  F I L E  W A S  G E N E R A T E D  <==---
    // #
    // # This file was generated by PRO Spark, C# Edition, Version 4.5
    // # Generated on 7/24/2013 4:11:01 PM
    // #
    // # Edits to this file may cause incorrect behavior and will be lost
    // # if the code is regenerated.
    // #
    // ############################################################################
	
	// Art Domain objects
	
    public partial class Artist : Entity<Artist>
	{
		public Artist() { }
        public Artist(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string LifeSpan { get; set; }
        public string Country { get; set; }
        public string Description { get; set; }
        public int TotalProducts { get; set; }
    }
	
    public partial class Cart : Entity<Cart>
	{
		public Cart() { }
        public Cart(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public string Cookie { get; set; }
        public DateTime? CartDate { get; set; }
        public int ItemCount { get; set; }
    }
	
    public partial class CartItem : Entity<CartItem>
	{
		public CartItem() { }
        public CartItem(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public int? CartId { get; set; }
        public int? ProductId { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }
    }
	
    public partial class Error : Entity<Error>
	{
		public Error() { }
        public Error(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public int? UserId { get; set; }
        public DateTime? ErrorDate { get; set; }
        public string IpAddress { get; set; }
        public string UserAgent { get; set; }
        public string Exception { get; set; }
        public string Message { get; set; }
        public string Everything { get; set; }
        public string HttpReferer { get; set; }
        public string PathAndQuery { get; set; }
    }
	
    public partial class Order : Entity<Order>
	{
		public Order() { }
        public Order(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public int? UserId { get; set; }
        public DateTime? OrderDate { get; set; }
        public double TotalPrice { get; set; }
        public int OrderNumber { get; set; }
        public int ItemCount { get; set; }
    }
	
    public partial class OrderDetail : Entity<OrderDetail>
	{
		public OrderDetail() { }
        public OrderDetail(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public int? OrderId { get; set; }
        public int? ProductId { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }
    }
	
    public partial class OrderNumber : Entity<OrderNumber>
	{
		public OrderNumber() { }
        public OrderNumber(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public int Number { get; set; }
    }
	
    public partial class Product : Entity<Product>
	{
		public Product() { }
        public Product(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int? ArtistId { get; set; }
        public string Image { get; set; }
        public double Price { get; set; }
        public int QuantitySold { get; set; }
        public double AvgStars { get; set; }
    }
	
    public partial class Rating : Entity<Rating>
	{
		public Rating() { }
        public Rating(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public int? UserId { get; set; }
        public int? ProductId { get; set; }
        public int Stars { get; set; }
    }
	
    public partial class User : Entity<User>
	{
		public User() { }
        public User(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public DateTime? SignupDate { get; set; }
        public int OrderCount { get; set; }
    }
}
